# -*- coding: utf-8 -*-
"""case study 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjI9jh2cLvykk3LMeTAu_EmXSEagSH-k
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_file = "archive (1).zip"  # apni file ka naam

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall("extracted_folder")

os.listdir("extracted_folder")

!unzip "archive (1).zip"

!ls

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt

train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    'Training',
    target_size=(128,128),
    batch_size=32,
    class_mode='categorical'
)

test_data = test_datagen.flow_from_directory(
    'Testing',
    target_size=(128,128),
    batch_size=32,
    class_mode='categorical'
)

print(train_data.class_indices)

model = keras.Sequential([
    keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64,(3,3),activation='relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128,(3,3),activation='relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Flatten(),
    keras.layers.Dense(128,activation='relu'),
    keras.layers.Dense(4,activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(train_data, epochs=5, validation_data=test_data)

img, label = next(test_data)

pred = model.predict(img)

plt.imshow(img[0])
plt.title("Predicted Class: " + str(np.argmax(pred[0])))
plt.show()