# -*- coding: utf-8 -*-
"""case study 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ta9pk4b7mfYKQO0HFBM63TGit4M5ADrx
"""

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

cifar = keras.datasets.cifar10
(x_train, y_train), (x_test, y_test) = cifar.load_data()
print(x_train.shape)

classes = ['airplane','automobile','bird','cat','deer',
           'dog','frog','horse','ship','truck']

plt.imshow(x_train[0])
plt.title(classes[y_train[0][0]])
plt.show()

x_train = x_train / 255.0
x_test = x_test / 255.0

model = keras.Sequential([
    keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=(32,32,3)),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Conv2D(64,(3,3),activation='relu'),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Conv2D(64,(3,3),activation='relu'),

    keras.layers.Flatten(),
    keras.layers.Dense(64,activation='relu'),
    keras.layers.Dense(10,activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=5)

test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Accuracy:", test_acc)

pred = model.predict(x_test)

plt.imshow(x_test[1])
plt.title("Predicted: " + classes[np.argmax(pred[1])])
plt.show()