# -*- coding: utf-8 -*-
"""case study 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7MAzqd7_ZTUFS9a0iLKcwgg1VFqsl0q
"""

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)

plt.imshow(x_train[0], cmap='gray')
plt.title(y_train[0])
plt.show()

x_train = x_train / 255.0
x_test = x_test / 255.0

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=5)

test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Accuracy:", test_acc)

pred = model.predict(x_test)

plt.imshow(x_test[1], cmap='gray')
plt.title("Predicted: " + str(np.argmax(pred[1])))
plt.show()